version: "2"
services:
  es:
    image: elasticsearch:7.5.2
    container_name: es_db
    environment:
      - discovery.type=single-node
  web:
    image: al3x3i/aiport_app
    depends_on:
      - es
    environment:
      - ES_RETRY_CONNECTIONS=10
      - ES_HOST=es_db
    command: python3 app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/code
